// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseInfoBtn: typeof import('./../components/BaseInfoBtn.vue')['default']
    BaseKPICard: typeof import('./../components/BaseKPICard.vue')['default']
    BaseSideFooter: typeof import('./../components/BaseSideFooter.vue')['default']
    BaseSocialMedia: typeof import('./../components/BaseSocialMedia.vue')['default']
    BaseThemeSwitchBtn: typeof import('./../components/BaseThemeSwitchBtn.vue')['default']
    BaseWeatherCard: typeof import('./../components/BaseWeatherCard.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    README: typeof import('./../components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
